"""first setup

Revision ID: c424086714cf
Revises: 925e5c71d967
Create Date: 2019-07-30 15:18:20.735502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c424086714cf'
down_revision = '925e5c71d967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('img', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'img')
    # ### end Alembic commands ###
